apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-test-4
  labels: 
    sda: sdsd
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    canary:
      stableService: express-active
      canaryService: express-preview
      trafficRouting:
        nginx:
          stableIngress: express-stable-ingress
      analysis:
        templates:
          - templateName: mixed-roll-tests
        startingStep: 1
      steps:
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {duration: 15s}
  selector:
    matchLabels:
      app: express-microservice
  template:
    metadata:
      labels:
        app: express-microservice
    spec:
      containers:
        - name: express-microservice
          image: xeonalex/guesbook:0.2
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
