apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-test-3
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    canary:
      analysis:
        templates:
          - templateName: mixed-roll-tests
        startingStep: 1
      steps:
        - pause: {duration: 10s}
        - setWeight: 50
        - pause: {duration: 10s}
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - name: guestbook-ui
          image: xeonalex/guesbook:0.3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
