apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: sleep-fail
        image: alpine:3.8
        command: [sleep 9999, sh, -c]
        args: [exit 0]
      restartPolicy: Never