apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "helm-guestbook.name" . }}
    release: {{ .Release.Name }}
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mixed-roll-tests
spec:
  metrics:
  - name: pass-roll-2
    count: 3
    interval: 20s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep-pass
                image: alpine:3.8
                command: [sh, -c]
                args: [exit 0]
              restartPolicy: Never
          backoffLimit: 0
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mixed-fail
spec:
  metrics:
  - name: randfail
    count: 3
    interval: 10s
    failureLimit: 3
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep-fail
                image: alpine:3.8
                command: [sh, -c]
                args: [FLIP=$(($(($RANDOM%10))%2)) && exit $FLIP]
              restartPolicy: Never
          backoffLimit: 0
