apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express-roll
  labels:
    somelb: somevsrrrrskkkk
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - image: xeonalex/guesbook:0.3
          name: express
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  minReadySeconds: 30
  strategy:
    canary:
      analysis:
        templates:
          - templateName: background
        startingStep: 1 # delay starting analysis run until setWeight: 40%
      steps:
        - setWeight: 20
        - pause: {duration: 60s}
        - setWeight: 75
        - pause: {duration: 15s}
        # - analysis:
        #     templates:
        #     - templateName: prometheus-template
        #     args:
        #     - name: service-name
        #       value: guestbook-svc.default.svc.cluster.local
        # - experiment:
        #     duration: 15s
        #     templates:
        #       - name: experiment-stable
        #         specRef: stable
        #         weight: 5
        #       - name: experiment-canary
        #         specRef: canary
        #         weight: 5
        #     # This experiment performs its own analysis by referencing one or more AnalysisTemplates
        #     # here. The success or failure of these runs will progress or abort the rollout respectively.
        #     analyses:
        #     - templateName: experiment-analysis
        #       requiredForCompletion: true
