apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express-roll
  labels:
    somelb: somevsskkkk
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - image: xeonalex/guesbook:0.1
          name: express
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  minReadySeconds: 30
  strategy:
    canary:
      # analysis:
        # templates:
          # - templateName: pass-always
        # startingStep: 1 # delay starting analysis run until setWeight: 40%
      steps:
        # - setWeight: 55
        - pause: {duration: 15s}
        # - analysis:
            # templates:
            # - templateName: mixed-tests
        # - setWeight: 75
        # - pause: {duration: 15s}
        # - analysis:
        #     templates:
        #     - templateName: prometheus-template
        #     args:
        #     - name: service-name
        #       value: guestbook-svc.default.svc.cluster.local
        # - experiment:
        #     duration: 15s
        #     templates:
        #     - name: canary
        #       specRef: canary
        #     # This experiment performs its own analysis by referencing one or more AnalysisTemplates
        #     # here. The success or failure of these runs will progress or abort the rollout respectively.
        #     analyses:
        #     - name: random-fail-experiment
        #       templateName: mixed-tests-experiment
        #       requiredForCompletion: true
