apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express-roll
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: express
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  minReadySeconds: 30
  strategy:
    canary:
      analysis:
        templates:
          - templateName: pass-always
          - templateName: mixed-tests
        startingStep: 1 # delay starting analysis run until setWeight: 40%
      steps:
        - setWeight: 25
        - pause: {duration: 1m}
