---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mixed-roll-tests
  labels:
    test: 'some'
spec:
  metrics:
  - name: pass-roll-2
    count: 3
    interval: 20s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep-pass
                image: alpine:3.8
                command: [sh, -c]
                args: [exit 0]
              restartPolicy: Never
          backoffLimit: 0
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mixed-fail
spec:
  metrics:
  - name: randfail
    # count: 3
    # interval: 10s
    successCondition: result == '173'
    # failureLimit: 3
    provider:
      # job:
      #   spec:
      #     template:
      #       spec:
      #         containers:
      #         - name: sleep-fail
      #           image: alpine:3.8
      #           command: [sh, -c]
      #           args: [FLIP=$(($(($RANDOM%10))%2)) && exit $FLIP]
      #         restartPolicy: Never
      #     backoffLimit: 0
      web:
        # url: "https://swapi.dev/api/people/1"
        url: "https://swapi.py4e.com/api/people/1"
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.height}"