apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    canary:
      steps:
        - pause:
            duration: 20s
        - analysis:
            templates:
              - templateName: mixed-roll-tests
        - setWeight: 50
        - pause:
            duration: 30s
  selector:
    matchLabels:
      app: express-microservice
  template:
    metadata:
      labels:
        app: express-microservice
    spec:
      containers:
        - name: express-microservice
          image: idanarbel/rollouts-demo:green
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
